# Generated by Django 4.2.16 on 2024-11-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
        ('Doctor', '0001_initial'),
        ('Recepcionista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacion', models.BooleanField()),
                ('fecha_hora', models.DateTimeField()),
                ('codigoCita', models.CharField(max_length=5)),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Doctor.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Paciente.paciente')),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Recepcionista.recepcionista')),
            ],
        ),
    ]
